version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency_api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://cache:6379
      - PORT=3000
      - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
      - BASE_URL=https://v6.exchangerate-api.com/v6
      - DB_PASSWORD=password

  db:
    image: postgres:15-alpine
    container_name: currency_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currency_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d currency_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis:alpine
    container_name: currency_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
